### ISSUE TITLE
Problem at container start

### ISSUE THREAD

**Issue by Slaca93** [0xste/grok-exporter#2]
Hello 0xste,

I have an issue when i starting the container.

I giving the config.yml at the start but i have this error in the logs:

podman logs bc6
Failed to load ${GROK_CONFIG_FILE}: open ${GROK_CONFIG_FILE}: no such file or directory

The file and the directory is exist.

This is how i am start:

podman run --name grok_exporter --detach --volume /opt/config/grok_exporter/config.yml:/etc/grok_exporter/config.yml -p 9144:9144 0xste\grok-exporter:latest

Can you help me please?

Regards,
Slaca

**Comment by 0xste** [comment]
Hi, apologies on late response, been on vacation

i've just ran it with the configuration i'd intended on using this for (detailed [here](https://github.com/flashbots/mev-boost/issues/370#issuecomment-1271715154))
`docker run --name grok --volume $(pwd)/config.yml:/etc/grok_exporter/config.yml 0xste/grok-exporter:latest`

Potentially it's something to do with your configuration file path or alternatively some quirk of Podman?
